@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjlhYWM1ODczMmYwOWMxZWE3YjE5N2JmIiwiaWF0IjoxNzcyODAyMDA3LCJleHAiOjE3NzM0MDY4MDd9.pNiMNLVg3SV-QDYgWkaCP1DhtMiGQ6OOyYsQ00Uuj6w

GET http://localhost:3000/api/characters
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjlhYWM1ODczMmYwOWMxZWE3YjE5N2JmIiwiaWF0IjoxNzcyODAyMDA3LCJleHAiOjE3NzM0MDY4MDd9.pNiMNLVg3SV-QDYgWkaCP1DhtMiGQ6OOyYsQ00Uuj6w

###
GET http://localhost:3000/api/characters?page=1&limit=2
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST http://localhost:3000/api/characters
Content-Type: application/json

{
    "name":"choso",
    "age":120,
    "species":"nisu",
    "role":"maldicion"
}

###
GET http://localhost:3000/api/characters/69a567446981aaac9b68c274
Content-Type: application/json
Authorization: Bearer {{token}}

###

PUT http://localhost:3000/api/characters/69aaa54561a6f961b3a5ae79
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"Choso",
    "age":125,
    "species":"Demonio",
    "role":"Maldicion"
}

###
DELETE http://localhost:3000/api/characters/69aaa54561a6f961b3a5ae79

###
GET http://localhost:3000/api/episodes
Content-Type: application/json
Authorization: Bearer { { token } }
###
POST http://localhost:3000/api/episodes
Content-Type: application/json

{   
    "title":"prueba1",
    "code":"1111",
    "summary":"nisu",
    "year":2026

}

###
GET http://localhost:3000/api/episodes/69aaa6e161a6f961b3a5ae81


###

PUT http://localhost:3000/api/episodes/69aaa6e161a6f961b3a5ae81
Content-Type: application/json

{
    "title":"prueba22221",
    "code":"6666",
    "summary":"NISU",
    "year":2026
}

###
DELETE http://localhost:3000/api/episodes/69aaa6e161a6f961b3a5ae81

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "carmen",
  "email": "carmen@gmail.com",
  "password": "1234"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "carmen@gmail.com",
  "password": "1234"
}
